// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: delete-feed-follow.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteFeedFollow = `-- name: DeleteFeedFollow :exec
DELETE
FROM feed_follows
WHERE id = $1
  AND user_id = $2
`

type DeleteFeedFollowParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteFeedFollow(ctx context.Context, arg DeleteFeedFollowParams) error {
	_, err := q.db.Exec(ctx, deleteFeedFollow, arg.ID, arg.UserID)
	return err
}
