// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: get-posts-by-user-id.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPostsByUserID = `-- name: GetPostsByUserID :many
SELECT posts.id, posts.title, posts.url, posts.description, posts.published_at, posts.created_at, posts.updated_at, posts.feed_id
FROM posts
         INNER JOIN feed_follows ON posts.feed_id = feed_follows.feed_id
WHERE feed_follows.user_id = $1
ORDER BY posts.published_at DESC
LIMIT $2
`

type GetPostsByUserIDParams struct {
	UserID pgtype.UUID
	Limit  int32
}

func (q *Queries) GetPostsByUserID(ctx context.Context, arg GetPostsByUserIDParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, getPostsByUserID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
