// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: mark-feed-fetched.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const markFeedFetched = `-- name: MarkFeedFetched :exec
UPDATE feeds
SET last_fetched_at = NOW(),
    updated_at      = NOW()
WHERE id = $1
`

func (q *Queries) MarkFeedFetched(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markFeedFetched, id)
	return err
}
